### ISSUE TITLE
Experimental setup

### ISSUE THREAD

**Issue by HakamShams** [DeepCube-org/uc3-public-notebooks#3]
Thank you for your work and for the dataset!

Could you please check the following:

- The used dynamic features are:
['Fpar_500m', 'Lai_500m', 'LST_Day_1km', 'LST_Night_1km', '1 km 16 days NDVI', '1 km 16 days EVI', 'era5_max_u10', 'era5_max_v10', 'era5_max_t2m', 'era5_max_tp', 'era5_min_u10', 'era5_min_v10', 'era5_min_t2m']

And the static ones are:
['dem_mean', 'aspect_mean', 'slope_mean', 'roads_density_2020', 'population_density']

So overall you used 13 dynamic and 5 static features.

- The inputs for a model (e.g., CNN) are all available features for day X. And the target is the variable burned_areas for day X+1 and maybe a comparison with the variable fwi for day X.

- You didn't use any pixel from the land cover [sea, water bodies, urban areas] during training/testing.

Is this correct?

**Comment by iprapas** [comment]
This is correct! We have open-sourced the code for training the models and new datasets https://github.com/Orion-AI-Lab/wildfire_forecasting . I invite you to have a look there for models that also use land cover information.

**Comment by HakamShams** [comment]
Ok, thank you!

**Comment by HakamShams** [comment]
Could you please explain this:

- For V0.1 Dataset:

From 2009-03-06 to 2018-12-31 the number of burned_areas 5715, number_of_fires 608, ignition_points 608
From 2019-01-01 to 2019-12-31 the number of burned_areas 297, number_of_fires 46, ignition_points 46
From 2020-01-01 to 2019-12-26 the number of burned_areas 412, number_of_fires 89, ignition_points 89

This is inconsistent with the numbers reported in the paper: ""Positive examples (pixels contained in burned areas) are all included in the datasets..... We do a time split using the years 2009-2018 for training, 2019 for validation and 2020 for testing. All the datasets consist of 15731 training (10380 non-fire, 5351 fire), 1337 validation (1075 non-fire,262 fire), and 1286 testing (975 non-fire, 311 fire) examples""?

- Are you sure if you want to predict for day X, you take the target from the next day X+1? This is inconsistent with the code and Notebook 3, where you take the input and the target from the same day 2020-08-31.

**Comment by iprapas** [comment]
Hello @HakamShams:

- Thank you for spotting this! The positive examples are counted on the pixel level, so the sum of the burned_areas. Both positives and negatives are taken in an extended fire season (Beginning of March to End of October) - We exclude the Late Autumn to Winter Period, that's why there is inconsistency between the burned_areas sum and the number of examples reported in the paper. 
- Yes, the way we have implemented to make sampling easy from the datacube is shifting the burned_areas + meteo variables one day back. So burned areas for day X+1, is on the datacube referred to in day X. Again thanks for spotting this! I will update the description of the datacube.

**Comment by HakamShams** [comment]
Thanks, this info helps :)
